-- 拆分緊急聯絡人「姓名+關係」黏在一起 — 2026-07-17
-- 來源Excel col18是"姓名/關係"合併(如 湯素玲父母)→拆成 emergency_contact_name=湯素玲, relation=父母。
-- 只拆結尾是關係詞(父母/配偶/子女/兄弟姊妹/祖父母/親戚)且 relation 為空的。兄弟姐妹→兄弟姊妹。idempotent。
-- 影響 80 人。

UPDATE public.employees SET emergency_contact_name = '余至順', emergency_contact_relation = '父母' WHERE id = 143;
UPDATE public.employees SET emergency_contact_name = '錢欣宜', emergency_contact_relation = '父母' WHERE id = 386;
UPDATE public.employees SET emergency_contact_name = '湯素玲', emergency_contact_relation = '父母' WHERE id = 62;
UPDATE public.employees SET emergency_contact_name = '吳東順', emergency_contact_relation = '父母' WHERE id = 406;
UPDATE public.employees SET emergency_contact_name = '韓巧伶', emergency_contact_relation = '兄弟姊妹' WHERE id = 148;
UPDATE public.employees SET emergency_contact_name = '林怡菁', emergency_contact_relation = '父母' WHERE id = 74;
UPDATE public.employees SET emergency_contact_name = '劉麗玟', emergency_contact_relation = '父母' WHERE id = 120;
UPDATE public.employees SET emergency_contact_name = '曾琬琪', emergency_contact_relation = '父母' WHERE id = 116;
UPDATE public.employees SET emergency_contact_name = '陳美娥', emergency_contact_relation = '父母' WHERE id = 114;
UPDATE public.employees SET emergency_contact_name = '連麗雪', emergency_contact_relation = '父母' WHERE id = 115;
UPDATE public.employees SET emergency_contact_name = '陳朋瀚', emergency_contact_relation = '配偶' WHERE id = 100;
UPDATE public.employees SET emergency_contact_name = '莫亞強', emergency_contact_relation = '父母' WHERE id = 211;
UPDATE public.employees SET emergency_contact_name = '張護議', emergency_contact_relation = '父母' WHERE id = 65;
UPDATE public.employees SET emergency_contact_name = '林美月', emergency_contact_relation = '父母' WHERE id = 141;
UPDATE public.employees SET emergency_contact_name = '范啟敏', emergency_contact_relation = '父母' WHERE id = 73;
UPDATE public.employees SET emergency_contact_name = '陳妙賢', emergency_contact_relation = '父母' WHERE id = 85;
UPDATE public.employees SET emergency_contact_name = '李永龍', emergency_contact_relation = '父母' WHERE id = 105;
UPDATE public.employees SET emergency_contact_name = '游混喨', emergency_contact_relation = '父母' WHERE id = 405;
UPDATE public.employees SET emergency_contact_name = '劉士豪', emergency_contact_relation = '父母' WHERE id = 409;
UPDATE public.employees SET emergency_contact_name = '蘇再來', emergency_contact_relation = '父母' WHERE id = 146;
UPDATE public.employees SET emergency_contact_name = '趙勇謀', emergency_contact_relation = '父母' WHERE id = 134;
UPDATE public.employees SET emergency_contact_name = '張珮萱', emergency_contact_relation = '配偶' WHERE id = 107;
UPDATE public.employees SET emergency_contact_name = '陳忠榮', emergency_contact_relation = '父母' WHERE id = 124;
UPDATE public.employees SET emergency_contact_name = '百述·翡戶依', emergency_contact_relation = '兄弟姊妹' WHERE id = 136;
UPDATE public.employees SET emergency_contact_name = '潘秋雯', emergency_contact_relation = '父母' WHERE id = 102;
UPDATE public.employees SET emergency_contact_name = '官振全', emergency_contact_relation = '配偶' WHERE id = 151;
UPDATE public.employees SET emergency_contact_name = '官彩秋', emergency_contact_relation = '父母' WHERE id = 75;
UPDATE public.employees SET emergency_contact_name = '陳卉湄', emergency_contact_relation = '父母' WHERE id = 132;
UPDATE public.employees SET emergency_contact_name = '林佑璘', emergency_contact_relation = '父母' WHERE id = 111;
UPDATE public.employees SET emergency_contact_name = '柯再源', emergency_contact_relation = '父母' WHERE id = 87;
UPDATE public.employees SET emergency_contact_name = '邱振裕', emergency_contact_relation = '父母' WHERE id = 112;
UPDATE public.employees SET emergency_contact_name = '吳姿靚', emergency_contact_relation = '父母' WHERE id = 214;
UPDATE public.employees SET emergency_contact_name = '周傑緯', emergency_contact_relation = '配偶' WHERE id = 397;
UPDATE public.employees SET emergency_contact_name = '林立絜', emergency_contact_relation = '父母' WHERE id = 400;
UPDATE public.employees SET emergency_contact_name = '池翠玉', emergency_contact_relation = '父母' WHERE id = 215;
UPDATE public.employees SET emergency_contact_name = '林志能', emergency_contact_relation = '父母' WHERE id = 99;
UPDATE public.employees SET emergency_contact_name = '張明東', emergency_contact_relation = '父母' WHERE id = 76;
UPDATE public.employees SET emergency_contact_name = '陳盈臻', emergency_contact_relation = '兄弟姊妹' WHERE id = 401;
UPDATE public.employees SET emergency_contact_name = '張文馨', emergency_contact_relation = '父母' WHERE id = 78;
UPDATE public.employees SET emergency_contact_name = '沈伊珊', emergency_contact_relation = '父母' WHERE id = 213;
UPDATE public.employees SET emergency_contact_name = '陳采筑', emergency_contact_relation = '父母' WHERE id = 72;
UPDATE public.employees SET emergency_contact_name = '黃莉涵', emergency_contact_relation = '父母' WHERE id = 80;
UPDATE public.employees SET emergency_contact_name = '陳彥如', emergency_contact_relation = '父母' WHERE id = 104;
UPDATE public.employees SET emergency_contact_name = '盧慶隨', emergency_contact_relation = '父母' WHERE id = 145;
UPDATE public.employees SET emergency_contact_name = '潘起揚', emergency_contact_relation = '父母' WHERE id = 101;
UPDATE public.employees SET emergency_contact_name = '林孝鏗', emergency_contact_relation = '父母' WHERE id = 208;
UPDATE public.employees SET emergency_contact_name = '陳文賢', emergency_contact_relation = '父母' WHERE id = 109;
UPDATE public.employees SET emergency_contact_name = '何永晴', emergency_contact_relation = '父母' WHERE id = 98;
UPDATE public.employees SET emergency_contact_name = '張庭瑋(女友)', emergency_contact_relation = '配偶' WHERE id = 113;
UPDATE public.employees SET emergency_contact_name = '阮氏心', emergency_contact_relation = '兄弟姊妹' WHERE id = 118;
UPDATE public.employees SET emergency_contact_name = '許世聞', emergency_contact_relation = '父母' WHERE id = 123;
UPDATE public.employees SET emergency_contact_name = '李芳慈', emergency_contact_relation = '父母' WHERE id = 77;
UPDATE public.employees SET emergency_contact_name = '徐榮國', emergency_contact_relation = '父母' WHERE id = 398;
UPDATE public.employees SET emergency_contact_name = '黃秀娟', emergency_contact_relation = '父母' WHERE id = 95;
UPDATE public.employees SET emergency_contact_name = '吳春蓉', emergency_contact_relation = '父母' WHERE id = 128;
UPDATE public.employees SET emergency_contact_name = '連小蘭', emergency_contact_relation = '父母' WHERE id = 127;
UPDATE public.employees SET emergency_contact_name = '陳金成', emergency_contact_relation = '父母' WHERE id = 125;
UPDATE public.employees SET emergency_contact_name = '張小鳳', emergency_contact_relation = '父母' WHERE id = 110;
UPDATE public.employees SET emergency_contact_name = '張若樺', emergency_contact_relation = '父母' WHERE id = 133;
UPDATE public.employees SET emergency_contact_name = '律智容', emergency_contact_relation = '父母' WHERE id = 108;
UPDATE public.employees SET emergency_contact_name = '林念潔', emergency_contact_relation = '父母' WHERE id = 106;
UPDATE public.employees SET emergency_contact_name = '曾禎', emergency_contact_relation = '配偶' WHERE id = 59;
UPDATE public.employees SET emergency_contact_name = '王沛婷', emergency_contact_relation = '配偶' WHERE id = 119;
UPDATE public.employees SET emergency_contact_name = '呂雨樵', emergency_contact_relation = '父母' WHERE id = 130;
UPDATE public.employees SET emergency_contact_name = '王源', emergency_contact_relation = '配偶' WHERE id = 69;
UPDATE public.employees SET emergency_contact_name = '楊淑芳', emergency_contact_relation = '父母' WHERE id = 384;
UPDATE public.employees SET emergency_contact_name = '陳韋天 正職工作的老闆(鳴躍室內設計)', emergency_contact_relation = '父母' WHERE id = 81;
UPDATE public.employees SET emergency_contact_name = '游秀敏', emergency_contact_relation = '父母' WHERE id = 71;
UPDATE public.employees SET emergency_contact_name = '顏靜薇', emergency_contact_relation = '配偶' WHERE id = 64;
UPDATE public.employees SET emergency_contact_name = '陳艷弘', emergency_contact_relation = '父母' WHERE id = 86;
UPDATE public.employees SET emergency_contact_name = '曾禎', emergency_contact_relation = '兄弟姊妹' WHERE id = 84;
UPDATE public.employees SET emergency_contact_name = '陳珍燕', emergency_contact_relation = '父母' WHERE id = 68;
UPDATE public.employees SET emergency_contact_name = '廖國享', emergency_contact_relation = '父母' WHERE id = 135;
UPDATE public.employees SET emergency_contact_name = '洪喜珠', emergency_contact_relation = '父母' WHERE id = 122;
UPDATE public.employees SET emergency_contact_name = '王中華 (哥哥)', emergency_contact_relation = '兄弟姊妹' WHERE id = 60;
UPDATE public.employees SET emergency_contact_name = '吳欣儒', emergency_contact_relation = '配偶' WHERE id = 58;
UPDATE public.employees SET emergency_contact_name = '廖瓊瑛', emergency_contact_relation = '父母' WHERE id = 140;
UPDATE public.employees SET emergency_contact_name = '蕭采軒 (朋友)', emergency_contact_relation = '兄弟姊妹' WHERE id = 212;
UPDATE public.employees SET emergency_contact_name = '陳幼兒', emergency_contact_relation = '父母' WHERE id = 209;
UPDATE public.employees SET emergency_contact_name = '陳其君', emergency_contact_relation = '配偶' WHERE id = 210;
