-- 更新門市稽核範本至 0812 版(新增「主動服務」7 個加分項 + 服務類重組 + 項目改名)
-- ─────────────────────────────────────────────────────────────
-- 來源:威士威稽核表0812_新增加分項ex.xlsx。6 大類各 100 分、6 類平均。
-- 變更 vs 0810:服務類群組重組(基礎服務30/主動服務=加分/櫃台20/新品上架15/送餐20/其他相關15);
--   加分項由 1 → 7(「四服務類 主動服務」整組 input_type=bonus);多題文字更新;★ 維持 3。
-- 每類別尾端保留「其他」catch-all(allot 0, input_type other)供臨時扣分。
-- 只換範本函式 → 只影響「之後新建」的稽核;既有稽核不動。calc_store_audit_score 不需改(通用)。
CREATE OR REPLACE FUNCTION public._create_store_audit_default_items(p_audit_id integer)
 RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO public.store_audit_items
    (audit_id, category_code, category_name, relation_group, group_allot, item_no, item_text, is_star, input_type)
  VALUES
  (p_audit_id, '一', '食品安全', '保存相關', 25, 1, '食材存放溫層', false, 'check'),
  (p_audit_id, '一', '食品安全', '保存相關', 25, 2, '冰箱食材是否有異樣、異味', false, 'check'),
  (p_audit_id, '一', '食品安全', '保存相關', 25, 3, '櫃台、廚房區須有消毒酒精，並標示「酒精」', false, 'check'),
  (p_audit_id, '一', '食品安全', '保存相關', 25, 4, '食材備品確實加封加蓋', false, 'check'),
  (p_audit_id, '一', '食品安全', '保存相關', 25, 5, '內場全區食材、物品擺放整齊', false, 'check'),
  (p_audit_id, '一', '食品安全', '保存相關', 25, 6, '食材、裝箱酒/飲料不落地，需有棧板', false, 'check'),
  (p_audit_id, '一', '食品安全', '保存相關', 25, 7, '調理區：清潔劑、消毒物品 須放置水槽下', false, 'check'),
  (p_audit_id, '一', '食品安全', '保存相關', 25, 8, '儲藏區：清潔劑、消毒物品 須放置獨立區', false, 'check'),
  (p_audit_id, '一', '食品安全', '保存相關', 25, 9, '冷藏冰箱存放：『熟>蔬果>肉>海鮮』', false, 'check'),
  (p_audit_id, '一', '食品安全', '人員相關', 25, 10, '廚房同仁服儀是否正確：帽子、口罩、手套', false, 'check'),
  (p_audit_id, '一', '食品安全', '人員相關', 25, 11, '同仁確實遵守洗手、消毒時機', false, 'check'),
  (p_audit_id, '一', '食品安全', '人員相關', 25, 12, '結帳後，手部確實消毒（或透明手套隔離）', false, 'check'),
  (p_audit_id, '一', '食品安全', '標示相關', 25, 13, '拆封後 食材、調料 確實標示『拆封日』', false, 'check'),
  (p_audit_id, '一', '食品安全', '標示相關', 25, 14, '分裝食材 須標示『拆封日、保存期限』', false, 'check'),
  (p_audit_id, '一', '食品安全', '標示相關', 25, 15, '食材均在保存期限內，無過期品', true, 'check'),
  (p_audit_id, '一', '食品安全', '標示相關', 25, 16, '清潔、消毒物品確實標示', false, 'check'),
  (p_audit_id, '一', '食品安全', '標示相關', 25, 17, '須標示單杯酒、暢飲酒『開瓶日期』', false, 'check'),
  (p_audit_id, '一', '食品安全', '分類相關', 25, 18, '砧板分類→熟食:白| 蔬菜生食:綠| 奶油起司:黃', false, 'check'),
  (p_audit_id, '一', '食品安全', '分類相關', 25, 19, '抹布分類', false, 'check'),
  (p_audit_id, '一', '食品安全', '其他', 0, 143, '', false, 'other'),
  (p_audit_id, '二', '公司政策', '表單相關', 40, 20, '值班日誌是否落實閱讀簽名', false, 'check'),
  (p_audit_id, '二', '公司政策', '表單相關', 40, 21, '值班日誌內是否落實個人上下班紀錄簽名', false, 'check'),
  (p_audit_id, '二', '公司政策', '表單相關', 40, 22, '『週月清潔表』落實清潔與複查', false, 'check'),
  (p_audit_id, '二', '公司政策', '表單相關', 40, 23, '油品檢查紀錄表是否確實', false, 'check'),
  (p_audit_id, '二', '公司政策', '表單相關', 40, 24, '廚房清潔表是否確實', false, 'check'),
  (p_audit_id, '二', '公司政策', '表單相關', 40, 25, '冰箱溫度檢查表是否確實', false, 'check'),
  (p_audit_id, '二', '公司政策', '表單相關', 40, 26, '靜電機檢查表是否確實', false, 'check'),
  (p_audit_id, '二', '公司政策', '表單相關', 40, 27, '製冰機檢查表是否確實', false, 'check'),
  (p_audit_id, '二', '公司政策', '表單相關', 40, 28, '濾心檢查表是否確實', false, 'check'),
  (p_audit_id, '二', '公司政策', '抽考訊息', 30, 29, '當前行銷活動', false, 'check'),
  (p_audit_id, '二', '公司政策', '抽考訊息', 30, 30, '當月主推酒款介紹', false, 'check'),
  (p_audit_id, '二', '公司政策', '抽考訊息', 30, 31, 'sop：', false, 'check'),
  (p_audit_id, '二', '公司政策', '其他相關', 30, 32, '食材斷貨：', false, 'check'),
  (p_audit_id, '二', '公司政策', '其他相關', 30, 33, '食材過多：', false, 'check'),
  (p_audit_id, '二', '公司政策', '其他相關', 30, 34, '行銷文宣效期', false, 'check'),
  (p_audit_id, '二', '公司政策', '其他相關', 30, 35, '進貨商品盡速上架', false, 'check'),
  (p_audit_id, '二', '公司政策', '其他相關', 30, 36, '確實遵守暢飲規則：給杯起算；同行列費用', false, 'check'),
  (p_audit_id, '二', '公司政策', '其他相關', 30, 37, '暢飲空瓶檢核：依循「流水號」開瓶', false, 'check'),
  (p_audit_id, '二', '公司政策', '其他相關', 30, 38, '抽查3樣庫存與現場實際對比 ►簽名', false, 'check'),
  (p_audit_id, '二', '公司政策', '其他', 0, 144, '', false, 'other'),
  (p_audit_id, '三', '品質類', '商品品質', 25, 39, '抽查出餐品質：', false, 'check'),
  (p_audit_id, '三', '品質類', '商品品質', 25, 40, '抽查出餐品質：', false, 'check'),
  (p_audit_id, '三', '品質類', '商品品質', 25, 41, '抽查出餐品質：', false, 'check'),
  (p_audit_id, '三', '品質類', '商品品質', 25, 42, '抽查出餐品質：', false, 'check'),
  (p_audit_id, '三', '品質類', '商品品質', 25, 43, '出餐時間，記錄：', false, 'check'),
  (p_audit_id, '三', '品質類', '商品品質', 25, 44, '白酒、清酒、氣泡酒需『預冷』', false, 'check'),
  (p_audit_id, '三', '品質類', '區域維護', 40, 45, '大門口擺放標準：門口目錄架、傘架、A字架', false, 'check'),
  (p_audit_id, '三', '品質類', '區域維護', 40, 46, '客席區整齊', false, 'check'),
  (p_audit_id, '三', '品質類', '區域維護', 40, 47, '自取區整齊標準（餐具、衛生紙）', false, 'check'),
  (p_audit_id, '三', '品質類', '區域維護', 40, 48, '暢飲區酒品擺放標準', false, 'check'),
  (p_audit_id, '三', '品質類', '區域維護', 40, 49, '商品櫃擺放標準', false, 'check'),
  (p_audit_id, '三', '品質類', '區域維護', 40, 50, '花車櫃擺放標準', false, 'check'),
  (p_audit_id, '三', '品質類', '區域維護', 40, 51, '三層櫃擺放標準', false, 'check'),
  (p_audit_id, '三', '品質類', '區域維護', 40, 52, '櫃檯區擺放標準', false, 'check'),
  (p_audit_id, '三', '品質類', '區域維護', 40, 53, '調理區擺放標準(餐期/非餐期)', false, 'check'),
  (p_audit_id, '三', '品質類', '區域維護', 40, 54, '倉儲區擺放標準', false, 'check'),
  (p_audit_id, '三', '品質類', '區域維護', 40, 55, '展示冰箱擺放標準', false, 'check'),
  (p_audit_id, '三', '品質類', '區域維護', 40, 56, '暢飲酒款依照規定品項及數量放置出來', false, 'check'),
  (p_audit_id, '三', '品質類', '區域維護', 40, 57, '廁所區擺放標準，廁所清潔記錄表簽名記錄', false, 'check'),
  (p_audit_id, '三', '品質類', '體感相關', 35, 58, '冷氣溫度適中', false, 'check'),
  (p_audit_id, '三', '品質類', '體感相關', 35, 59, '音樂音量適中', false, 'check'),
  (p_audit_id, '三', '品質類', '體感相關', 35, 60, '音樂種類合適', false, 'check'),
  (p_audit_id, '三', '品質類', '體感相關', 35, 61, '海報、文宣放置位子適中、不翹起或損壞', false, 'check'),
  (p_audit_id, '三', '品質類', '體感相關', 35, 62, '同仁服儀標準：制服乾淨整齊+帽子', false, 'check'),
  (p_audit_id, '三', '品質類', '其他', 0, 145, '', false, 'other'),
  (p_audit_id, '四', '服務類', '基礎服務', 30, 63, '保持親切微笑；適時運用禮貌用語', false, 'check'),
  (p_audit_id, '四', '服務類', '基礎服務', 30, 64, '顧客進店10秒內主動招呼，並引導入座', false, 'check'),
  (p_audit_id, '四', '服務類', '基礎服務', 30, 65, '清楚介紹：消費流程及用餐方式', false, 'check'),
  (p_audit_id, '四', '服務類', '基礎服務', 30, 66, '暢飲：確實介紹取酒機使用方式與暢飲規則', false, 'check'),
  (p_audit_id, '四', '服務類', '基礎服務', 30, 67, '發現顧客有需求或問題時，主動協助處理', false, 'check'),
  (p_audit_id, '四', '服務類', '基礎服務', 30, 68, '確認顧客餐點是否齊全，避免漏餐', false, 'check'),
  (p_audit_id, '四', '服務類', '基礎服務', 30, 69, '客人想換酒款飲用，須提供『洗杯』服務', false, 'check'),
  (p_audit_id, '四', '服務類', '主動服務', 0, 70, '主動於適當時機推薦『特色酒款、商品』', false, 'bonus'),
  (p_audit_id, '四', '服務類', '主動服務', 0, 71, '主動進行試吃試喝活動', false, 'bonus'),
  (p_audit_id, '四', '服務類', '主動服務', 0, 72, '客人在商品櫃前，主動上前關心並介紹商品', false, 'bonus'),
  (p_audit_id, '四', '服務類', '主動服務', 0, 73, '結帳前，主動關心客人用餐感受', false, 'bonus'),
  (p_audit_id, '四', '服務類', '主動服務', 0, 74, '客人太醉狀況，主動協助需求>>停止時間', false, 'bonus'),
  (p_audit_id, '四', '服務類', '主動服務', 0, 75, '能主動辨識熟客並適切關懷，提供貼心服務', false, 'bonus'),
  (p_audit_id, '四', '服務類', '主動服務', 0, 76, '店內燈光、佈置合適 (因應節慶主題/活動適時更換)', false, 'bonus'),
  (p_audit_id, '四', '服務類', '櫃台相關', 20, 77, '點餐完成後，確實向顧客複誦餐點內容及數量', false, 'check'),
  (p_audit_id, '四', '服務類', '櫃台相關', 20, 78, 'ＰＯＳ正確進單並依流程通知廚房/出餐單位', false, 'check'),
  (p_audit_id, '四', '服務類', '櫃台相關', 20, 79, '確實複誦餐點內容 ► 告知總金額', false, 'check'),
  (p_audit_id, '四', '服務類', '櫃台相關', 20, 80, '確實複誦收取方式 (現金、信用卡)', false, 'check'),
  (p_audit_id, '四', '服務類', '櫃台相關', 20, 81, '顧客離店時，主動致謝並歡迎再次光臨', false, 'check'),
  (p_audit_id, '四', '服務類', '新品上架', 15, 82, '新品上市，確認新品標示、POS機品項價格、牌價/風味卡，資訊一致且正確', false, 'check'),
  (p_audit_id, '四', '服務類', '送餐相關', 20, 83, '餐點到齊時，告知客人', false, 'check'),
  (p_audit_id, '四', '服務類', '送餐相關', 20, 84, '送餐位置不可從客人身後進餐', false, 'check'),
  (p_audit_id, '四', '服務類', '送餐相關', 20, 85, '餐點超過15分鐘出餐，需致歉久候', false, 'check'),
  (p_audit_id, '四', '服務類', '送餐相關', 20, 86, '若有吃完的空盤，須適時收回(非分享盤)', false, 'check'),
  (p_audit_id, '四', '服務類', '其他相關', 15, 87, '保持理性溝通，不可與他人吵架、打架', true, 'check'),
  (p_audit_id, '四', '服務類', '其他', 0, 146, '', false, 'other'),
  (p_audit_id, '五', '清潔類', '大門區', 10, 88, '天花板：檢視是否蜘蛛網；燈光正常', false, 'check'),
  (p_audit_id, '五', '清潔類', '大門區', 10, 89, '玻璃：髒、指紋', false, 'check'),
  (p_audit_id, '五', '清潔類', '大門區', 10, 90, '文宣海報：位子正確、乾淨', false, 'check'),
  (p_audit_id, '五', '清潔類', '大門區', 10, 91, '地板：乾淨、無菸蒂', false, 'check'),
  (p_audit_id, '五', '清潔類', '大門區', 10, 92, '是否看起來像營業中', false, 'check'),
  (p_audit_id, '五', '清潔類', '客席區', 20, 93, '桌面不黏膩', false, 'check'),
  (p_audit_id, '五', '清潔類', '客席區', 20, 94, '桌面衛生紙方向正確、數量適中', false, 'check'),
  (p_audit_id, '五', '清潔類', '客席區', 20, 95, '椅子坐面乾淨不黏膩', false, 'check'),
  (p_audit_id, '五', '清潔類', '客席區', 20, 96, '桌下地板乾淨無菜渣', false, 'check'),
  (p_audit_id, '五', '清潔類', '客席區', 20, 97, '沙發乾淨整齊', false, 'check'),
  (p_audit_id, '五', '清潔類', '客席區', 20, 98, '沙發底乾淨', false, 'check'),
  (p_audit_id, '五', '清潔類', '客席區', 20, 99, '店內燈光正常運作', false, 'check'),
  (p_audit_id, '五', '清潔類', '客席區', 20, 100, '燈罩乾淨無灰塵', false, 'check'),
  (p_audit_id, '五', '清潔類', '客席區', 20, 101, '紙箱區立即整理，不放置客席區', false, 'check'),
  (p_audit_id, '五', '清潔類', '櫃檯/吧台/自取區/取酒機', 10, 102, '櫃檯後方乾淨整齊，無同仁私人物品', false, 'check'),
  (p_audit_id, '五', '清潔類', '櫃檯/吧台/自取區/取酒機', 10, 103, '吧區後方乾淨整齊，無同仁私人物品', false, 'check'),
  (p_audit_id, '五', '清潔類', '櫃檯/吧台/自取區/取酒機', 10, 104, '起司展示冰箱乾淨整齊，無同仁私人物品', false, 'check'),
  (p_audit_id, '五', '清潔類', '櫃檯/吧台/自取區/取酒機', 10, 105, '餐具自取區乾淨整齊', false, 'check'),
  (p_audit_id, '五', '清潔類', '櫃檯/吧台/自取區/取酒機', 10, 106, '檸檬水是否每日更新', false, 'check'),
  (p_audit_id, '五', '清潔類', '櫃檯/吧台/自取區/取酒機', 10, 107, '水杯是否倒蓋；是否有灰塵', false, 'check'),
  (p_audit_id, '五', '清潔類', '櫃檯/吧台/自取區/取酒機', 10, 108, '取酒機整齊乾淨', false, 'check'),
  (p_audit_id, '五', '清潔類', '廚房區', 20, 109, '調理區不可有紙箱，包含:冷藏冰箱、層架', false, 'check'),
  (p_audit_id, '五', '清潔類', '廚房區', 20, 110, '地板乾淨乾燥', false, 'check'),
  (p_audit_id, '五', '清潔類', '廚房區', 20, 111, '桌面乾淨整齊', false, 'check'),
  (p_audit_id, '五', '清潔類', '廚房區', 20, 112, '層架乾淨整齊', false, 'check'),
  (p_audit_id, '五', '清潔類', '廚房區', 20, 113, '烤箱乾淨，積碳不會過多', false, 'check'),
  (p_audit_id, '五', '清潔類', '廚房區', 20, 114, '炸爐油品顏色正常，不可過黑', false, 'check'),
  (p_audit_id, '五', '清潔類', '廚房區', 20, 115, '微波爐內外乾淨', false, 'check'),
  (p_audit_id, '五', '清潔類', '廚房區', 20, 116, '燈光亮度正常運作', false, 'check'),
  (p_audit_id, '五', '清潔類', '廚房區', 20, 117, '抽油煙機乾淨、正常運作', false, 'check'),
  (p_audit_id, '五', '清潔類', '廚房區', 20, 118, '香菸、檳榔不可放置廚房區域', true, 'check'),
  (p_audit_id, '五', '清潔類', '廚房區', 20, 119, '冷藏冰箱乾淨整齊，無超過5公分的結霜', false, 'check'),
  (p_audit_id, '五', '清潔類', '廚房區', 20, 120, '冷凍冰箱乾淨整齊，無超過5公分的結霜', false, 'check'),
  (p_audit_id, '五', '清潔類', '廚房區', 20, 121, '飯鍋內外乾淨', false, 'check'),
  (p_audit_id, '五', '清潔類', '廁所區', 15, 122, '備品充足(擦手紙、衛生紙、洗手乳、酒精)', false, 'check'),
  (p_audit_id, '五', '清潔類', '廁所區', 15, 123, '地板乾淨乾燥', false, 'check'),
  (p_audit_id, '五', '清潔類', '廁所區', 15, 124, '無異味', false, 'check'),
  (p_audit_id, '五', '清潔類', '廁所區', 15, 125, '馬桶乾淨無異味', false, 'check'),
  (p_audit_id, '五', '清潔類', '廁所區', 15, 126, '水槽乾淨、水流進出順暢', false, 'check'),
  (p_audit_id, '五', '清潔類', '廁所區', 15, 127, '水槽旁檯面乾淨乾燥', false, 'check'),
  (p_audit_id, '五', '清潔類', '廁所區', 15, 128, '每間廁所是否放置酒精瓶(1/2以上酒精)', false, 'check'),
  (p_audit_id, '五', '清潔類', '倉庫區', 15, 129, '冷凍冰箱擺放定位', false, 'check'),
  (p_audit_id, '五', '清潔類', '倉庫區', 15, 130, '確實加封加蓋', false, 'check'),
  (p_audit_id, '五', '清潔類', '倉庫區', 15, 131, '確實有棧板', false, 'check'),
  (p_audit_id, '五', '清潔類', '倉庫區', 15, 132, '清潔品、消毒品不亂放', false, 'check'),
  (p_audit_id, '五', '清潔類', '倉庫區', 15, 133, '同仁物品有特定區域，不亂放', false, 'check'),
  (p_audit_id, '五', '清潔類', '後門區', 10, 134, '垃圾車、廚餘桶均確實蓋好蓋子', false, 'check'),
  (p_audit_id, '五', '清潔類', '後門區', 10, 135, '地板乾淨乾燥無異味', false, 'check'),
  (p_audit_id, '五', '清潔類', '其他', 0, 147, '', false, 'other'),
  (p_audit_id, '六', '遠端稽核', '監控畫面', 50, 136, '同仁在廚區料理時，是否戴手套口罩帽子', false, 'check'),
  (p_audit_id, '六', '遠端稽核', '監控畫面', 50, 137, '上班時是否確實大洗手', false, 'check'),
  (p_audit_id, '六', '遠端稽核', '監控畫面', 50, 138, '洗手時機', false, 'check'),
  (p_audit_id, '六', '遠端稽核', '監控畫面', 50, 139, '人員閒置過久', false, 'check'),
  (p_audit_id, '六', '遠端稽核', '調撥進貨', 15, 140, '進貨調撥驗收超過七天', false, 'check'),
  (p_audit_id, '六', '遠端稽核', 'google評論', 35, 141, '正向評論的回覆', false, 'check'),
  (p_audit_id, '六', '遠端稽核', 'google評論', 35, 142, '負向評論是否回報，並與主管討論回覆', false, 'check'),
  (p_audit_id, '六', '遠端稽核', '其他', 0, 148, '', false, 'other');
END $function$;

-- 拿掉舊的通用加分列(0812 起改用「主動服務」7 個專屬加分項,通用加分重複、紙本也沒有)
CREATE OR REPLACE FUNCTION public._trg_store_audit_after_insert()
 RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
BEGIN
  PERFORM public._create_store_audit_default_items(NEW.id);
  RETURN NEW;
END $function$;

NOTIFY pgrst, 'reload schema';
