export const CRM_EVENTS = {
  'crm.lead.scored': {
    domain: 'crm',
    action: 'lead.scored',
    version: 1,
    description: '潛在客戶評分更新',
    payload: {
      customer_id: { type: 'string', required: true },
      customer_name: { type: 'string', required: true },
      old_score: { type: 'number', required: false },
      new_score: { type: 'number', required: true },
    },
  },
  'crm.opportunity.won': {
    domain: 'crm',
    action: 'opportunity.won',
    version: 1,
    description: '商機成交',
    payload: {
      opportunity_id: { type: 'string', required: true },
      customer: { type: 'string', required: true },
      amount: { type: 'number', required: true },
    },
  },
  'crm.segment.changed': {
    domain: 'crm',
    action: 'segment.changed',
    version: 1,
    description: '客戶分群變更',
    payload: {
      customer_id: { type: 'string', required: true },
      old_segment: { type: 'string', required: false },
      new_segment: { type: 'string', required: true },
    },
  },
  'crm.campaign.triggered': {
    domain: 'crm',
    action: 'campaign.triggered',
    version: 1,
    description: '行銷活動觸發',
    payload: {
      campaign_id: { type: 'string', required: true },
      campaign_name: { type: 'string', required: true },
      target_count: { type: 'number', required: false },
    },
  },
  'crm.lead.created': {
    domain: 'crm',
    action: 'lead.created',
    version: 1,
    description: '線索建立',
    payload: {
      lead_id: { type: 'number', required: true },
      name: { type: 'string', required: true },
      source: { type: 'string', required: false },
    },
  },
  'crm.lead.converted': {
    domain: 'crm',
    action: 'lead.converted',
    version: 1,
    description: '線索轉換為客戶',
    payload: {
      lead_id: { type: 'number', required: true },
      customer_id: { type: 'number', required: true },
      deal_id: { type: 'number', required: false },
    },
  },
  'crm.activity.created': {
    domain: 'crm',
    action: 'activity.created',
    version: 1,
    description: '活動建立',
    payload: {
      activity_id: { type: 'number', required: true },
      type: { type: 'string', required: true },
      subject: { type: 'string', required: true },
      assignee: { type: 'string', required: false },
    },
  },
  'crm.activity.overdue': {
    domain: 'crm',
    action: 'activity.overdue',
    version: 1,
    description: '活動逾期',
    payload: {
      activity_id: { type: 'number', required: true },
      subject: { type: 'string', required: true },
      assignee: { type: 'string', required: false },
      due_date: { type: 'string', required: true },
    },
  },
  'crm.quote.generated': {
    domain: 'crm',
    action: 'quote.generated',
    version: 1,
    description: '從商機產生報價單',
    payload: {
      opportunity_id: { type: 'number', required: true },
      quotation_id: { type: 'number', required: true },
      amount: { type: 'number', required: true },
    },
  },
  'crm.form.submitted': {
    domain: 'crm',
    action: 'form.submitted',
    version: 1,
    description: '表單提交',
    payload: {
      form_id: { type: 'number', required: true },
      form_name: { type: 'string', required: true },
      submission_id: { type: 'number', required: true },
      data: { type: 'object', required: true },
    },
  },
}
