export const FINANCE_EVENTS = {
  'finance.ar.created': {
    domain: 'finance',
    action: 'ar.created',
    version: 1,
    description: '應收帳款建立',
    payload: {
      ar_id: { type: 'string', required: true },
      invoice_number: { type: 'string', required: true },
      customer: { type: 'string', required: true },
      amount: { type: 'number', required: true },
      source: { type: 'string', required: false },
      source_id: { type: 'string', required: false },
    },
  },
  'finance.ap.created': {
    domain: 'finance',
    action: 'ap.created',
    version: 1,
    description: '應付帳款建立',
    payload: {
      ap_id: { type: 'string', required: true },
      bill_number: { type: 'string', required: true },
      supplier: { type: 'string', required: true },
      amount: { type: 'number', required: true },
      po_ref: { type: 'string', required: false },
    },
  },
  'finance.journal.posted': {
    domain: 'finance',
    action: 'journal.posted',
    version: 1,
    description: '傳票過帳',
    payload: {
      entry_id: { type: 'string', required: true },
      entry_number: { type: 'string', required: true },
      amount: { type: 'number', required: true },
      description: { type: 'string', required: false },
    },
  },
  'finance.voucher.auto_posted': {
    domain: 'finance',
    action: 'voucher.auto_posted',
    version: 1,
    description: '傳票自動拋轉完成（F-A2 規則引擎）',
    payload: {
      entry_id: { type: 'string', required: true },
      entry_number: { type: 'string', required: false },
      doc_type: { type: 'string', required: true },
      source_type: { type: 'string', required: true },
      source_id: { type: 'string', required: true },
      total_amount: { type: 'number', required: false },
    },
  },
  'finance.settlement.fee': {
    domain: 'finance',
    action: 'settlement.fee',
    version: 1,
    description: '信用卡請款批次結算手續費（F-D1 — 供拋轉引擎產「借 手續費支出/貸 應收卡款」傳票）',
    payload: {
      batch_id: { type: 'string', required: true },
      fee_amount: { type: 'number', required: true },
      gross_amount: { type: 'number', required: false },
      net_amount: { type: 'number', required: false },
      batch_number: { type: 'string', required: false },
      acquirer: { type: 'string', required: false },
      deposit_date: { type: 'string', required: false },
    },
  },
  'finance.invoice.issued': {
    domain: 'finance',
    action: 'invoice.issued',
    version: 1,
    description: '電子發票開立完成（F-B3 — 供進銷項憑證檔自動彙入 vat_output_documents）',
    payload: {
      payment_id: { type: 'string', required: true },
      invoice_number: { type: 'string', required: true },
      provider: { type: 'string', required: false },
      already_issued: { type: 'boolean', required: false },
    },
  },
  'finance.invoice.voided': {
    domain: 'finance',
    action: 'invoice.voided',
    version: 1,
    description: '電子發票同日作廢（F0501）— 憑證檔移除該筆銷項',
    payload: {
      payment_id: { type: 'string', required: true },
      invoice_number: { type: 'string', required: false },
      provider: { type: 'string', required: false },
    },
  },
  'finance.invoice.allowance': {
    domain: 'finance',
    action: 'invoice.allowance',
    version: 1,
    description: '電子發票跨日折讓（D0401）— 憑證檔另立負額折讓（格式 33）',
    payload: {
      payment_id: { type: 'string', required: true },
      invoice_number: { type: 'string', required: false },
      provider: { type: 'string', required: false },
    },
  },
  'finance.payment.recorded': {
    domain: 'finance',
    action: 'payment.recorded',
    version: 1,
    description: '收付款記錄',
    payload: {
      payment_id: { type: 'string', required: true },
      type: { type: 'string', required: true },
      amount: { type: 'number', required: true },
      reference_id: { type: 'string', required: false },
    },
  },
}
