export const HR_EVENTS = {
  'hr.employee.onboarded': {
    domain: 'hr',
    action: 'employee.onboarded',
    version: 1,
    description: '新員工報到完成',
    payload: {
      employee_id: { type: 'string', required: true },
      name: { type: 'string', required: true },
      dept: { type: 'string', required: false },
      position: { type: 'string', required: false },
    },
  },
  'hr.leave.requested': {
    domain: 'hr',
    action: 'leave.requested',
    version: 1,
    description: '請假申請提交',
    payload: {
      leave_id:    { type: 'string', required: true },
      employee_id: { type: 'string', required: true },
      employee:    { type: 'string', required: true },
      type:        { type: 'string', required: true },
      days:        { type: 'number', required: true },
      start_date:  { type: 'string', required: false },
      end_date:    { type: 'string', required: false },
    },
  },
  'hr.leave.approved': {
    domain: 'hr',
    action: 'leave.approved',
    version: 1,
    description: '請假單核准',
    payload: {
      leave_id: { type: 'string', required: true },
      employee: { type: 'string', required: true },
      type:     { type: 'string', required: true },
      days:     { type: 'number', required: true },
    },
  },
  'hr.leave.rejected': {
    domain: 'hr',
    action: 'leave.rejected',
    version: 1,
    description: '請假單退回',
    payload: {
      leave_id:    { type: 'string', required: true },
      employee_id: { type: 'string', required: true },
      employee:    { type: 'string', required: true },
      reason:      { type: 'string', required: false },
    },
  },
  'hr.overtime.requested': {
    domain: 'hr',
    action: 'overtime.requested',
    version: 1,
    description: '加班申請提交',
    payload: {
      overtime_id: { type: 'string', required: true },
      employee_id: { type: 'string', required: true },
      employee:    { type: 'string', required: true },
      hours:       { type: 'number', required: false },
      date:        { type: 'string', required: false },
    },
  },
  'hr.overtime.approved': {
    domain: 'hr',
    action: 'overtime.approved',
    version: 1,
    description: '加班單核准',
    payload: {
      overtime_id: { type: 'string', required: true },
      employee_id: { type: 'string', required: true },
      employee:    { type: 'string', required: true },
      hours:       { type: 'number', required: false },
    },
  },
  'hr.overtime.rejected': {
    domain: 'hr',
    action: 'overtime.rejected',
    version: 1,
    description: '加班單退回',
    payload: {
      overtime_id: { type: 'string', required: true },
      employee_id: { type: 'string', required: true },
      employee:    { type: 'string', required: true },
      reason:      { type: 'string', required: false },
    },
  },
  'hr.salary.calculated': {
    domain: 'hr',
    action: 'salary.calculated',
    version: 1,
    description: '薪資計算完成',
    payload: {
      employee_id: { type: 'string', required: true },
      month: { type: 'string', required: true },
      net_salary: { type: 'number', required: true },
    },
  },
  'hr.expense.approved': {
    domain: 'hr',
    action: 'expense.approved',
    version: 1,
    description: '費用報銷核准',
    payload: {
      expense_id:  { type: 'string', required: true },
      employee:    { type: 'string', required: true },
      category:    { type: 'string', required: true },
      amount:      { type: 'number', required: true },
      description: { type: 'string', required: false },
      date:        { type: 'string', required: false },
    },
  },
  'hr.expense.rejected': {
    domain: 'hr',
    action: 'expense.rejected',
    version: 1,
    description: '費用報銷退回',
    payload: {
      expense_id:  { type: 'string', required: true },
      employee_id: { type: 'string', required: true },
      employee:    { type: 'string', required: true },
      reason:      { type: 'string', required: false },
    },
  },
  'hr.expense_request.submitted': {
    domain: 'hr',
    action: 'expense_request.submitted',
    version: 1,
    description: '費用申請提交',
    payload: {
      request_id:  { type: 'string', required: true },
      employee_id: { type: 'string', required: true },
      employee:    { type: 'string', required: true },
      amount:      { type: 'number', required: true },
      category:    { type: 'string', required: false },
      description: { type: 'string', required: false },
    },
  },
  'hr.expense_request.approved': {
    domain: 'hr',
    action: 'expense_request.approved',
    version: 1,
    description: '費用申請核准',
    payload: {
      request_id:  { type: 'string', required: true },
      employee_id: { type: 'string', required: true },
      employee:    { type: 'string', required: true },
      amount:      { type: 'number', required: true },
    },
  },
  'hr.expense_request.rejected': {
    domain: 'hr',
    action: 'expense_request.rejected',
    version: 1,
    description: '費用申請退回',
    payload: {
      request_id:  { type: 'string', required: true },
      employee_id: { type: 'string', required: true },
      employee:    { type: 'string', required: true },
      reason:      { type: 'string', required: false },
    },
  },
  'hr.business_trip.requested': {
    domain: 'hr',
    action: 'business_trip.requested',
    version: 1,
    description: '出差申請提交',
    payload: {
      trip_id:     { type: 'string', required: true },
      employee_id: { type: 'string', required: true },
      employee:    { type: 'string', required: true },
      destination: { type: 'string', required: false },
      start_date:  { type: 'string', required: false },
      end_date:    { type: 'string', required: false },
    },
  },
  'hr.business_trip.approved': {
    domain: 'hr',
    action: 'business_trip.approved',
    version: 1,
    description: '出差申請核准',
    payload: {
      trip_id:     { type: 'string', required: true },
      employee_id: { type: 'string', required: true },
      employee:    { type: 'string', required: true },
    },
  },
  'hr.business_trip.rejected': {
    domain: 'hr',
    action: 'business_trip.rejected',
    version: 1,
    description: '出差申請退回',
    payload: {
      trip_id:     { type: 'string', required: true },
      employee_id: { type: 'string', required: true },
      employee:    { type: 'string', required: true },
      reason:      { type: 'string', required: false },
    },
  },
  'hr.clock_correction.requested': {
    domain: 'hr',
    action: 'clock_correction.requested',
    version: 1,
    description: '補打卡申請提交',
    payload: {
      correction_id: { type: 'string', required: true },
      employee_id:   { type: 'string', required: true },
      employee:      { type: 'string', required: true },
      date:          { type: 'string', required: false },
      reason:        { type: 'string', required: false },
    },
  },
  'hr.clock_correction.approved': {
    domain: 'hr',
    action: 'clock_correction.approved',
    version: 1,
    description: '補打卡申請核准',
    payload: {
      correction_id: { type: 'string', required: true },
      employee_id:   { type: 'string', required: true },
      employee:      { type: 'string', required: true },
    },
  },
  'hr.clock_correction.rejected': {
    domain: 'hr',
    action: 'clock_correction.rejected',
    version: 1,
    description: '補打卡申請退回',
    payload: {
      correction_id: { type: 'string', required: true },
      employee_id:   { type: 'string', required: true },
      employee:      { type: 'string', required: true },
      reason:        { type: 'string', required: false },
    },
  },
  'hr.clock.in': {
    domain: 'hr',
    action: 'clock.in',
    version: 1,
    description: '員工打卡上班',
    payload: {
      employee_id: { type: 'string', required: true },
      timestamp: { type: 'string', required: true },
      location: { type: 'string', required: false },
    },
  },
  'hr.clock.out': {
    domain: 'hr',
    action: 'clock.out',
    version: 1,
    description: '員工打卡下班',
    payload: {
      employee_id: { type: 'string', required: true },
      timestamp: { type: 'string', required: true },
      hours: { type: 'number', required: false },
    },
  },
  'hr.offboarding.started': {
    domain: 'hr',
    action: 'offboarding.started',
    version: 1,
    description: '員工離職流程啟動',
    payload: {
      employee_id: { type: 'string', required: true },
      name: { type: 'string', required: true },
      dept: { type: 'string', required: false },
      last_working_date: { type: 'string', required: true },
    },
  },
  'hr.probation.expiring': {
    domain: 'hr',
    action: 'probation.expiring',
    version: 1,
    description: '試用期即將到期',
    payload: {
      employee_id: { type: 'string', required: true },
      name: { type: 'string', required: true },
      end_date: { type: 'string', required: true },
      days_remaining: { type: 'number', required: true },
    },
  },
  'hr.survey.completed': {
    domain: 'hr',
    action: 'survey.completed',
    version: 1,
    description: '滿意度調查已結束',
    payload: {
      survey_id: { type: 'string', required: true },
      title: { type: 'string', required: true },
      response_count: { type: 'number', required: true },
      overall_score: { type: 'number', required: false },
    },
  },
  'hr.attrition.high_risk': {
    domain: 'hr',
    action: 'attrition.high_risk',
    version: 1,
    description: '員工離職風險達高風險',
    payload: {
      employee_id: { type: 'string', required: true },
      name: { type: 'string', required: true },
      risk_score: { type: 'number', required: true },
      factors: { type: 'array', required: false },
    },
  },
  'hr.payslip.sent': {
    domain: 'hr',
    action: 'payslip.sent',
    version: 1,
    description: '薪資單已發送',
    payload: {
      employee_id: { type: 'string', required: true },
      month:       { type: 'string', required: true },
      channel:     { type: 'string', required: false },
    },
  },
  'hr.candidate.applied': {
    domain: 'hr',
    action: 'candidate.applied',
    version: 1,
    description: '新候選人建檔',
    payload: {
      candidate_id: { type: 'string', required: true },
      name:         { type: 'string', required: true },
      job_id:       { type: 'string', required: false },
      source:       { type: 'string', required: false },
    },
  },
  'hr.interview.scheduled': {
    domain: 'hr',
    action: 'interview.scheduled',
    version: 1,
    description: '面試已排定',
    payload: {
      interview_id:   { type: 'string', required: true },
      candidate_id:   { type: 'string', required: true },
      candidate_name: { type: 'string', required: true },
      round:          { type: 'string', required: true },
      scheduled_at:   { type: 'string', required: true },
      interviewer_id: { type: 'string', required: false },
    },
  },
  'hr.hire.approved': {
    domain: 'hr',
    action: 'hire.approved',
    version: 1,
    description: '錄取簽呈最終核准',
    payload: {
      offer_letter_id: { type: 'string', required: true },
      candidate_id:    { type: 'string', required: true },
      candidate_name:  { type: 'string', required: true },
      position:        { type: 'string', required: true },
      start_date:      { type: 'string', required: false },
    },
  },
  'hr.offer.sent': {
    domain: 'hr',
    action: 'offer.sent',
    version: 1,
    description: '錄取通知書已發送給候選人',
    payload: {
      offer_letter_id: { type: 'string', required: true },
      candidate_id:    { type: 'string', required: true },
      candidate_name:  { type: 'string', required: true },
      sent_at:         { type: 'string', required: true },
    },
  },
}
