export const LMS_EVENTS = {
  'lms.course.published': {
    domain: 'lms',
    action: 'course.published',
    version: 1,
    description: '課程發布',
    payload: {
      course_id: { type: 'string', required: true },
      title: { type: 'string', required: true },
      category: { type: 'string', required: false },
      created_by: { type: 'string', required: false },
    },
  },
  'lms.enrollment.created': {
    domain: 'lms',
    action: 'enrollment.created',
    version: 1,
    description: '學員報名課程',
    payload: {
      enrollment_id: { type: 'string', required: true },
      course_id: { type: 'string', required: true },
      course_title: { type: 'string', required: true },
      employee_id: { type: 'string', required: true },
      employee_name: { type: 'string', required: false },
      enrolled_by: { type: 'string', required: false },
      due_date: { type: 'string', required: false },
    },
  },
  'lms.lesson.completed': {
    domain: 'lms',
    action: 'lesson.completed',
    version: 1,
    description: '學員完成課程單元',
    payload: {
      enrollment_id: { type: 'string', required: true },
      lesson_id: { type: 'string', required: true },
      lesson_title: { type: 'string', required: true },
      course_id: { type: 'string', required: true },
      employee_id: { type: 'string', required: true },
      score: { type: 'number', required: false },
      time_spent_seconds: { type: 'number', required: false },
    },
  },
  'lms.course.completed': {
    domain: 'lms',
    action: 'course.completed',
    version: 1,
    description: '學員完成整門課程',
    payload: {
      enrollment_id: { type: 'string', required: true },
      course_id: { type: 'string', required: true },
      course_title: { type: 'string', required: true },
      employee_id: { type: 'string', required: true },
      employee_name: { type: 'string', required: false },
      score: { type: 'number', required: false },
      passed: { type: 'boolean', required: true },
    },
  },
  'lms.certificate.issued': {
    domain: 'lms',
    action: 'certificate.issued',
    version: 1,
    description: '發放結業證書',
    payload: {
      certificate_id: { type: 'string', required: true },
      certificate_number: { type: 'string', required: true },
      course_id: { type: 'string', required: true },
      course_title: { type: 'string', required: true },
      employee_id: { type: 'string', required: true },
      employee_name: { type: 'string', required: false },
      score: { type: 'number', required: false },
    },
  },
  'lms.quiz.submitted': {
    domain: 'lms',
    action: 'quiz.submitted',
    version: 1,
    description: '學員提交測驗',
    payload: {
      enrollment_id: { type: 'string', required: true },
      lesson_id: { type: 'string', required: true },
      employee_id: { type: 'string', required: true },
      score: { type: 'number', required: true },
      passed: { type: 'boolean', required: true },
    },
  },
}
