export const POS_EVENTS = {
  'pos.transaction.completed': {
    domain: 'pos',
    action: 'transaction.completed',
    version: 1,
    description: 'POS 交易完成',
    payload: {
      transaction_id: { type: 'string', required: true },
      transaction_number: { type: 'string', required: true },
      store: { type: 'string', required: true },
      cashier: { type: 'string', required: true },
      total: { type: 'number', required: true },
      payment_method: { type: 'string', required: false },
      items: { type: 'array', required: false },
      customer_id: { type: 'number', required: false },
      points_used: { type: 'number', required: false },
    },
  },
  'pos.transaction.refunded': {
    domain: 'pos',
    action: 'transaction.refunded',
    version: 1,
    description: 'POS 交易退款',
    payload: {
      refund_id: { type: 'string', required: true },
      original_transaction_id: { type: 'string', required: true },
      store: { type: 'string', required: true },
      cashier: { type: 'string', required: false },
      customer_id: { type: 'number', required: false },
      refund_amount: { type: 'number', required: true },
      original_total: { type: 'number', required: false },
      reason: { type: 'string', required: false },
      items: { type: 'array', required: false },
    },
  },
  'pos.shift.opened': {
    domain: 'pos',
    action: 'shift.opened',
    version: 1,
    description: 'POS 班次開始',
    payload: {
      shift_id: { type: 'string', required: true },
      store: { type: 'string', required: true },
      cashier: { type: 'string', required: true },
      opening_cash: { type: 'number', required: true },
    },
  },
  'pos.shift.closed': {
    domain: 'pos',
    action: 'shift.closed',
    version: 1,
    description: 'POS 班次結束',
    payload: {
      shift_id: { type: 'string', required: true },
      store: { type: 'string', required: true },
      cashier: { type: 'string', required: true },
      closing_cash: { type: 'number', required: true },
      cash_difference: { type: 'number', required: false },
    },
  },
  'pos.access.revoked': {
    domain: 'pos',
    action: 'access.revoked',
    version: 1,
    description: 'POS 存取權限撤銷（離職流程）',
    payload: {
      employee_id: { type: 'string', required: true },
      name: { type: 'string', required: true },
      reason: { type: 'string', required: false },
    },
  },
  'pos.order.submitted': {
    domain: 'pos',
    action: 'order.submitted',
    version: 1,
    description: '顧客透過 QR 自助點餐送出',
    payload: {
      order_id:      { type: 'string',  required: true  },
      store_id:      { type: 'string',  required: true  },
      table_id:      { type: 'string',  required: false },
      table_number:  { type: 'string',  required: false },
      item_count:    { type: 'number',  required: true  },
      auto_approved: { type: 'boolean', required: true  },
    },
  },
  'pos.order.confirmed': {
    domain: 'pos',
    action: 'order.confirmed',
    version: 1,
    description: '店員確認 QR 點餐並送往廚房',
    payload: {
      order_id:     { type: 'string', required: true  },
      store_id:     { type: 'string', required: false },
      confirmed_by: { type: 'string', required: false },
    },
  },
  'pos.order.ready': {
    domain: 'pos',
    action: 'order.ready',
    version: 1,
    description: '廚房完成製作，訂單可取餐',
    payload: {
      order_id:     { type: 'string', required: true  },
      store_id:     { type: 'string', required: false },
      table_number: { type: 'string', required: false },
    },
  },
}
