export const WMS_EVENTS = {
  'wms.shipment.completed': {
    domain: 'wms',
    action: 'shipment.completed',
    version: 1,
    description: '出貨單完成（已掃描、已出貨）',
    payload: {
      shipment_id: { type: 'string', required: true },
      customer: { type: 'string', required: true },
      order_ref: { type: 'string', required: true },
      total_amount: { type: 'number', required: true },
      items: { type: 'array', required: false },
      carrier: { type: 'string', required: false },
      tracking_number: { type: 'string', required: false },
    },
  },
  'wms.stock.adjusted': {
    domain: 'wms',
    action: 'stock.adjusted',
    version: 1,
    description: '庫存數量調整（盤點差異、損耗等）',
    payload: {
      sku_name: { type: 'string', required: true },
      sku_id: { type: 'string', required: false },
      old_qty: { type: 'number', required: true },
      new_qty: { type: 'number', required: true },
      reason: { type: 'string', required: true },
      warehouse_id: { type: 'string', required: false },
    },
  },
  'wms.stock.below_reorder': {
    domain: 'wms',
    action: 'stock.below_reorder',
    version: 1,
    description: '庫存低於再訂購點',
    payload: {
      items: { type: 'array', required: true },
    },
  },
  'wms.transfer.completed': {
    domain: 'wms',
    action: 'transfer.completed',
    version: 1,
    description: '庫存調撥完成',
    payload: {
      transfer_id: { type: 'string', required: true },
      from_warehouse: { type: 'string', required: true },
      to_warehouse: { type: 'string', required: true },
      items: { type: 'array', required: true },
    },
  },
  'wms.return.received': {
    domain: 'wms',
    action: 'return.received',
    version: 1,
    description: '退貨已收貨',
    payload: {
      return_id: { type: 'string', required: true },
      return_number: { type: 'string', required: true },
      customer: { type: 'string', required: true },
      reason: { type: 'string', required: true },
      items: { type: 'array', required: true },
    },
  },
  'wms.return.restocked': {
    domain: 'wms',
    action: 'return.restocked',
    version: 1,
    description: '退貨品檢通過並入庫',
    payload: {
      return_id: { type: 'string', required: true },
      return_number: { type: 'string', required: true },
      items: { type: 'array', required: true },
      scrapped_items: { type: 'array', required: false },
    },
  },
  'wms.return.scrapped': {
    domain: 'wms',
    action: 'return.scrapped',
    version: 1,
    description: '退貨品檢不合格全數報廢',
    payload: {
      return_id: { type: 'string', required: true },
      return_number: { type: 'string', required: true },
      items: { type: 'array', required: true },
    },
  },
  'wms.auto_reorder.triggered': {
    domain: 'wms',
    action: 'auto_reorder.triggered',
    version: 1,
    description: '自動補貨觸發，產生草稿採購單',
    payload: {
      purchase_orders: { type: 'array', required: true },
      skipped_items: { type: 'array', required: false },
      triggered_by: { type: 'string', required: true },
    },
  },
  'wms.kit.assembled': {
    domain: 'wms',
    action: 'kit.assembled',
    version: 1,
    description: '組合商品組裝完成',
    payload: {
      kit_id: { type: 'string', required: true },
      kit_sku: { type: 'string', required: true },
      quantity: { type: 'number', required: true },
      components: { type: 'array', required: true },
    },
  },
  'wms.kit.disassembled': {
    domain: 'wms',
    action: 'kit.disassembled',
    version: 1,
    description: '組合商品拆解',
    payload: {
      kit_id: { type: 'string', required: true },
      kit_sku: { type: 'string', required: true },
      quantity: { type: 'number', required: true },
      components: { type: 'array', required: true },
    },
  },
  'wms.access.revoked': {
    domain: 'wms',
    action: 'access.revoked',
    version: 1,
    description: 'WMS 存取權限撤銷（離職流程）',
    payload: {
      employee_id: { type: 'string', required: true },
      name: { type: 'string', required: true },
      reason: { type: 'string', required: false },
    },
  },
  'wms.stock.reserved': {
    domain: 'wms',
    action: 'stock.reserved',
    version: 1,
    description: '庫存預留（銷售訂單確認）',
    payload: {
      order_id: { type: 'string', required: true },
      order_number: { type: 'string', required: true },
      items: { type: 'array', required: true },
    },
  },
}
